#PBS -q UCTlong /
#PBS -l nodes=1:ppn=10:series600 /
#PBS -N RNAseqTBtest_trim_at40 /
#PBS -V /
#PBS -M lmbjas002@myuct.ac.za /
#PBS -m ae /
dir="/scratch/lmbjas002/CASS_RNAseq/CASS_1st_lot_samples/fastq_files"
cd "$dir"
for i in $(ls *.f*q.gz)
do
  echo "processing $i initiated"
  file="${dir}/${i}"
  sh /home/lmbjas002/Server_Version/RNAseq/TBgenome/TB_RNAseq_pipeline.sh "$file" 10
  echo "processing $i completed"
done
